id: P010798
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 2021-12-20 10:25:00.847730
source_metadata:
  id: bdr:W1KG16591
  title: གསོ་རིག་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    c8e4c71172524b1abf603a73cbdaa62f:
      image_group_id: I2PD18181
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
